// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/email/email.proto

package go_micro_srv_email

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorRequest struct {
	// 接口出现的位置
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 错误的信息
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorRequest) Reset()         { *m = ErrorRequest{} }
func (m *ErrorRequest) String() string { return proto.CompactTextString(m) }
func (*ErrorRequest) ProtoMessage()    {}
func (*ErrorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_840f7b8354a62044, []int{0}
}

func (m *ErrorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorRequest.Unmarshal(m, b)
}
func (m *ErrorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorRequest.Marshal(b, m, deterministic)
}
func (m *ErrorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorRequest.Merge(m, src)
}
func (m *ErrorRequest) XXX_Size() int {
	return xxx_messageInfo_ErrorRequest.Size(m)
}
func (m *ErrorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorRequest proto.InternalMessageInfo

func (m *ErrorRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ErrorRequest) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type ErrorResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResult) Reset()         { *m = ErrorResult{} }
func (m *ErrorResult) String() string { return proto.CompactTextString(m) }
func (*ErrorResult) ProtoMessage()    {}
func (*ErrorResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_840f7b8354a62044, []int{1}
}

func (m *ErrorResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResult.Unmarshal(m, b)
}
func (m *ErrorResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResult.Marshal(b, m, deterministic)
}
func (m *ErrorResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResult.Merge(m, src)
}
func (m *ErrorResult) XXX_Size() int {
	return xxx_messageInfo_ErrorResult.Size(m)
}
func (m *ErrorResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResult.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResult proto.InternalMessageInfo

type CodeRequest struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeRequest) Reset()         { *m = CodeRequest{} }
func (m *CodeRequest) String() string { return proto.CompactTextString(m) }
func (*CodeRequest) ProtoMessage()    {}
func (*CodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_840f7b8354a62044, []int{2}
}

func (m *CodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeRequest.Unmarshal(m, b)
}
func (m *CodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeRequest.Marshal(b, m, deterministic)
}
func (m *CodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeRequest.Merge(m, src)
}
func (m *CodeRequest) XXX_Size() int {
	return xxx_messageInfo_CodeRequest.Size(m)
}
func (m *CodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CodeRequest proto.InternalMessageInfo

func (m *CodeRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *CodeRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CodeResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeResult) Reset()         { *m = CodeResult{} }
func (m *CodeResult) String() string { return proto.CompactTextString(m) }
func (*CodeResult) ProtoMessage()    {}
func (*CodeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_840f7b8354a62044, []int{3}
}

func (m *CodeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeResult.Unmarshal(m, b)
}
func (m *CodeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeResult.Marshal(b, m, deterministic)
}
func (m *CodeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeResult.Merge(m, src)
}
func (m *CodeResult) XXX_Size() int {
	return xxx_messageInfo_CodeResult.Size(m)
}
func (m *CodeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeResult.DiscardUnknown(m)
}

var xxx_messageInfo_CodeResult proto.InternalMessageInfo

type MessageRequest struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_840f7b8354a62044, []int{4}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *MessageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type MessageResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResult) Reset()         { *m = MessageResult{} }
func (m *MessageResult) String() string { return proto.CompactTextString(m) }
func (*MessageResult) ProtoMessage()    {}
func (*MessageResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_840f7b8354a62044, []int{5}
}

func (m *MessageResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResult.Unmarshal(m, b)
}
func (m *MessageResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResult.Marshal(b, m, deterministic)
}
func (m *MessageResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResult.Merge(m, src)
}
func (m *MessageResult) XXX_Size() int {
	return xxx_messageInfo_MessageResult.Size(m)
}
func (m *MessageResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResult.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResult proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ErrorRequest)(nil), "go.micro.srv.email.ErrorRequest")
	proto.RegisterType((*ErrorResult)(nil), "go.micro.srv.email.ErrorResult")
	proto.RegisterType((*CodeRequest)(nil), "go.micro.srv.email.CodeRequest")
	proto.RegisterType((*CodeResult)(nil), "go.micro.srv.email.CodeResult")
	proto.RegisterType((*MessageRequest)(nil), "go.micro.srv.email.MessageRequest")
	proto.RegisterType((*MessageResult)(nil), "go.micro.srv.email.MessageResult")
}

func init() { proto.RegisterFile("proto/email/email.proto", fileDescriptor_840f7b8354a62044) }

var fileDescriptor_840f7b8354a62044 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xcd, 0x4d, 0xcc, 0xcc, 0x81, 0x90, 0x7a, 0x60, 0x11, 0x21, 0xa1, 0xf4, 0x7c,
	0xbd, 0xdc, 0xcc, 0xe4, 0xa2, 0x7c, 0xbd, 0xe2, 0xa2, 0x32, 0x3d, 0xb0, 0x8c, 0x92, 0x19, 0x17,
	0x8f, 0x6b, 0x51, 0x51, 0x7e, 0x51, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x10, 0x1f, 0x17,
	0x53, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x53, 0x66, 0x8a, 0x90, 0x18, 0x17,
	0x5b, 0x4a, 0x6a, 0x49, 0x62, 0x66, 0x8e, 0x04, 0x13, 0x58, 0x0c, 0xca, 0x53, 0xe2, 0xe5, 0xe2,
	0x86, 0xea, 0x2b, 0x2e, 0xcd, 0x29, 0x51, 0x32, 0xe7, 0xe2, 0x76, 0xce, 0x4f, 0x49, 0x45, 0x32,
	0xa5, 0x24, 0x1f, 0x66, 0x4a, 0x49, 0xbe, 0x90, 0x04, 0x17, 0x7b, 0x72, 0x7e, 0x5e, 0x49, 0x6a,
	0x5e, 0x09, 0xd4, 0x18, 0x18, 0x57, 0x89, 0x87, 0x8b, 0x0b, 0xa2, 0x11, 0x6c, 0x8c, 0x15, 0x17,
	0x9f, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x3a, 0x19, 0x26, 0xf1, 0x73, 0xf1, 0xc2, 0xf5, 0x82, 0x0c,
	0x33, 0xfa, 0xc2, 0xc8, 0xc5, 0xea, 0x0a, 0xf2, 0xa4, 0x90, 0x0f, 0x17, 0x2b, 0xd8, 0xb1, 0x42,
	0x0a, 0x7a, 0x98, 0x41, 0xa0, 0x87, 0xec, 0x7f, 0x29, 0x79, 0x3c, 0x2a, 0xc0, 0x4e, 0x64, 0x10,
	0xf2, 0xe4, 0x62, 0x01, 0x39, 0x59, 0x08, 0xab, 0x52, 0xa4, 0x50, 0x90, 0x92, 0xc3, 0xad, 0x00,
	0x6a, 0x54, 0x10, 0x17, 0x3b, 0xd4, 0xcd, 0x42, 0x4a, 0xd8, 0x14, 0xa3, 0x06, 0x86, 0x94, 0x22,
	0x5e, 0x35, 0x10, 0x33, 0x93, 0xd8, 0xc0, 0x91, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xee,
	0x62, 0xa0, 0xe1, 0x07, 0x02, 0x00, 0x00,
}
