// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/email/email.proto

package go_micro_srv_email

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Email service

type EmailService interface {
	Error(ctx context.Context, in *ErrorRequest, opts ...client.CallOption) (*ErrorResult, error)
	Code(ctx context.Context, in *CodeRequest, opts ...client.CallOption) (*CodeResult, error)
	Message(ctx context.Context, in *MessageRequest, opts ...client.CallOption) (*MessageResult, error)
}

type emailService struct {
	c    client.Client
	name string
}

func NewEmailService(name string, c client.Client) EmailService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.email"
	}
	return &emailService{
		c:    c,
		name: name,
	}
}

func (c *emailService) Error(ctx context.Context, in *ErrorRequest, opts ...client.CallOption) (*ErrorResult, error) {
	req := c.c.NewRequest(c.name, "Email.Error", in)
	out := new(ErrorResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailService) Code(ctx context.Context, in *CodeRequest, opts ...client.CallOption) (*CodeResult, error) {
	req := c.c.NewRequest(c.name, "Email.Code", in)
	out := new(CodeResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailService) Message(ctx context.Context, in *MessageRequest, opts ...client.CallOption) (*MessageResult, error) {
	req := c.c.NewRequest(c.name, "Email.Message", in)
	out := new(MessageResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Email service

type EmailHandler interface {
	Error(context.Context, *ErrorRequest, *ErrorResult) error
	Code(context.Context, *CodeRequest, *CodeResult) error
	Message(context.Context, *MessageRequest, *MessageResult) error
}

func RegisterEmailHandler(s server.Server, hdlr EmailHandler, opts ...server.HandlerOption) error {
	type email interface {
		Error(ctx context.Context, in *ErrorRequest, out *ErrorResult) error
		Code(ctx context.Context, in *CodeRequest, out *CodeResult) error
		Message(ctx context.Context, in *MessageRequest, out *MessageResult) error
	}
	type Email struct {
		email
	}
	h := &emailHandler{hdlr}
	return s.Handle(s.NewHandler(&Email{h}, opts...))
}

type emailHandler struct {
	EmailHandler
}

func (h *emailHandler) Error(ctx context.Context, in *ErrorRequest, out *ErrorResult) error {
	return h.EmailHandler.Error(ctx, in, out)
}

func (h *emailHandler) Code(ctx context.Context, in *CodeRequest, out *CodeResult) error {
	return h.EmailHandler.Code(ctx, in, out)
}

func (h *emailHandler) Message(ctx context.Context, in *MessageRequest, out *MessageResult) error {
	return h.EmailHandler.Message(ctx, in, out)
}
