// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for User service

type UserService interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResult, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResult, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResult, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResult, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.user"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResult, error) {
	req := c.c.NewRequest(c.name, "User.Create", in)
	out := new(CreateResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResult, error) {
	req := c.c.NewRequest(c.name, "User.Update", in)
	out := new(UpdateResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResult, error) {
	req := c.c.NewRequest(c.name, "User.Delete", in)
	out := new(DeleteResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResult, error) {
	req := c.c.NewRequest(c.name, "User.Read", in)
	out := new(ReadResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	Create(context.Context, *CreateRequest, *CreateResult) error
	Update(context.Context, *UpdateRequest, *UpdateResult) error
	Delete(context.Context, *DeleteRequest, *DeleteResult) error
	Read(context.Context, *ReadRequest, *ReadResult) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		Create(ctx context.Context, in *CreateRequest, out *CreateResult) error
		Update(ctx context.Context, in *UpdateRequest, out *UpdateResult) error
		Delete(ctx context.Context, in *DeleteRequest, out *DeleteResult) error
		Read(ctx context.Context, in *ReadRequest, out *ReadResult) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) Create(ctx context.Context, in *CreateRequest, out *CreateResult) error {
	return h.UserHandler.Create(ctx, in, out)
}

func (h *userHandler) Update(ctx context.Context, in *UpdateRequest, out *UpdateResult) error {
	return h.UserHandler.Update(ctx, in, out)
}

func (h *userHandler) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResult) error {
	return h.UserHandler.Delete(ctx, in, out)
}

func (h *userHandler) Read(ctx context.Context, in *ReadRequest, out *ReadResult) error {
	return h.UserHandler.Read(ctx, in, out)
}
